Add tests for module classes and addc command
AY2223S1-CS2103T-T12-1/tp pull request #129
Opened 2022-10-10 15:30 UTC by njxue

1. `TypicalModuleClasses` and `TypicalSessions` contain objects that can be used throughout test cases
2. `ModuleClassBuilder` can be used to create `ModuleClass` objects for module classes in `TypicalModuleClasses`

2022-10-10 16:14 UTC, RezwanArefin01 requested changes
Looks good. One or two minor nits.

2022-10-10 16:14 UTC, RezwanArefin01 commented on src/test/data/JsonSerializableTaAssistTest/invalidStudentTaAssist.json
> +  }]
This is an invalid files, so there was no need to do this. :joy:

2022-10-10 16:14 UTC, RezwanArefin01 commented on src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
> +        AddcCommand addCS1101SCommand = new AddcCommand(CS1101S);
Should `addCS1101SCommand` be `addCs1101sCommand` instead? as per coding standard.

2022-10-10 16:14 UTC, RezwanArefin01 commented on src/test/java/seedu/taassist/model/moduleclass/UniqueModuleClassListTest.java
> +public class UniqueModuleClassListTest {
PR #130 removes the Unique* classes.

2022-10-12 07:00 UTC, njxue commented on src/test/data/JsonSerializableTaAssistTest/invalidStudentTaAssist.json
> +  }]
This file is used to test an invalid student field (the invalid email) and not the json file, I think. One of the test cases fails (with read json file error) if I do not change it

2022-10-12 07:43 UTC, RezwanArefin01 requested changes
One minor coding standard issue left over.

2022-10-12 07:43 UTC, RezwanArefin01 commented on src/test/java/seedu/taassist/logic/commands/AddcCommandTest.java
> +        AddcCommand addCS1231SCommand = new AddcCommand(CS1231S);
Leftover coding standard issue.

2022-10-12 12:57 UTC, RezwanArefin01 approved these changes
LGTM!

2022-10-12 13:08 UTC, merged