Add test for json adapted module class
AY2223S1-CS2103T-T12-1/tp pull request #145
Opened 2022-10-12 14:49 UTC by optionalemon

2022-10-12 16:07 UTC, njxue requested changes

2022-10-12 16:07 UTC, njxue commented on src/test/java/seedu/taassist/testutil/TypicalModuleClasses.java
> +    public static final ModuleClass CS2100 = new ModuleClassBuilder().withName("CS1231S")
```suggestion
    public static final ModuleClass CS2100 = new ModuleClassBuilder().withName("CS2100")
```

2022-10-13 08:27 UTC, Berted approved these changes
LGTM! Just an optional comment regarding code duplication that you can ignore :)

2022-10-13 08:27 UTC, Berted commented on src/test/java/seedu/taassist/storage/JsonAdaptedModuleClassTest.java
> +        List<JsonAdaptedSession> sessions = new ArrayList<>();
Perhaps consider abstracting this away to a static method to reduce code duplication.

2022-10-14 01:47 UTC, njxue approved these changes

2022-10-14 13:12 UTC, merged