Fix inconsistency between `addc` and `deletec` commands.
AY2223S1-CS2103T-T12-1/tp pull request #224
Opened 2022-10-26 14:30 UTC by Bubbl3T

Resolves #143.

2022-10-26 19:19 UTC, Bubbl3T commented
Resolves #235.

2022-10-27 02:04 UTC, njxue requested changes

2022-10-27 02:04 UTC, njxue commented on src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
> +    public static String getCommandMessage(Set<ModuleClass> existingClasses, Set<ModuleClass> nonExistentClasses) {
Maybe perform a requireAllNonNull check here

2022-10-27 03:33 UTC, Bubbl3T commented on src/main/java/seedu/taassist/logic/commands/DeletecCommand.java
> +    public static String getCommandMessage(Set<ModuleClass> existingClasses, Set<ModuleClass> nonExistentClasses) {
Alright!

2022-10-27 03:43 UTC, njxue approved these changes

2022-10-27 03:52 UTC, merged