Fix class names mismatch betweenn command result and remaining parts of GUI
AY2223S1-CS2103T-T12-1/tp pull request #321
Opened 2022-10-29 16:06 UTC by njxue

Resolves class names in #255 but not session names.

2022-11-01 12:04 UTC, Berted requested changes
Nice work! Albeit I have a few nits regarding some sections of the code, but overall, good work!

2022-11-01 12:04 UTC, Berted commented on src/main/java/seedu/taassist/model/TaAssist.java
> +        if (foundModuleClass.isEmpty()) {
Perhaps consider using the method `Optional::orElseThrow` to simplify this code section?

2022-11-01 12:04 UTC, Berted commented on src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
> +    public void execute_indexOutOfRange_throwsCommandException() throws Exception {
Any reason why this method throws an `Exception`?

2022-11-01 12:04 UTC, Berted commented on src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
> +    private static class ModelStubWithMultipleStudents extends ModelStub {
Good catch!

2022-11-01 14:43 UTC, njxue commented on src/test/java/seedu/taassist/logic/commands/AssignCommandTest.java
> +    public void execute_indexOutOfRange_throwsCommandException() throws Exception {
oops forgot to delete

2022-11-02 14:15 UTC, Berted approved these changes
LGTM!

2022-11-02 14:24 UTC, merged